### ISSUE TITLE
API page - Text not aligned with bullets (Firefox)

### ISSUE THREAD

**Issue by jseppi** [TNRIS/iswp2017#191]
In Firefox the text that should be next to each bullet point is instead displayed below as if on the next line.

<img width="573" alt="screen shot 2016-05-16 at 12 15 38 am" src="https://cloud.githubusercontent.com/assets/697848/15280858/028a048a-1afb-11e6-9ecc-1ed6d8b7d638.png">

**Comment by jseppi** [comment]
This should fix it

```css
.route-method-path {
  display: inline-block;
}
```
